# Generated by Django 5.1 on 2024-09-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
